# ITQ

<img src= "img/LogoITQ.png" width="50"/>

# PAO 2025-2026

**Nombre:** *Israel Pabon* 

**Fecha:** *25/03/2026*

<img src= "img/ITQLogoING.jpeg" width="150"/>

# 2.1 Estandarización

![logo](img/PyLogoING.jpeg)

**Israel Pabon**

In [3]:
from sklearn import preprocessing
import numpy as np

In [4]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [5]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [6]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [7]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [8]:
# Comprobar si las matrices estandarizadas son iguales
print(np.array_equal(X_train_std, X_train_2_std))

True


In [ ]:
https://github.com/Flaquencio/machinelearning2026/blob/main/ipynb/Estandarizacion.ipynb